## PyTorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.0+cu121


## Introduction to tensors

### Creating tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# get tensor back as python int
scalar.item()

7

In [6]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [7, 6, 2],
                        [9, 1, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [7, 6, 2],
         [9, 1, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [7, 6, 2],
        [9, 1, 5]])

In [17]:
TENSOR[0].shape

torch.Size([3, 3])

In [18]:
TENSOR[0][0]

tensor([1, 2, 3])

In [19]:
TENSOR[0][0][0]

tensor(1)

### Random tensors

They are important because many neural networks start with tensors full of random numbers and then adjust those numbers to better represent the data.

In [20]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5068, 0.4540, 0.4179, 0.9130],
        [0.1453, 0.9178, 0.4499, 0.6311],
        [0.4214, 0.3047, 0.1148, 0.1510]])

In [21]:
random_tensor.ndim

2

In [22]:
random_tensor = torch.rand(1, 3, 4)
random_tensor

tensor([[[0.0897, 0.6433, 0.3435, 0.9547],
         [0.3774, 0.0257, 0.9092, 0.2408],
         [0.5736, 0.8851, 0.5742, 0.4775]]])

In [23]:
random_tensor.ndim

3

In [24]:
# Create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # colour chanels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [25]:
torch.rand(size=(3, 3))

tensor([[0.6326, 0.2162, 0.9427],
        [0.1389, 0.1571, 0.7454],
        [0.6831, 0.0495, 0.1645]])

### Zeroes and ones

In [26]:
# Create a tensor of all zeroes
zeroes = torch.zeros(size=(3, 4))
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
zeroes * random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [28]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
ones.dtype

torch.float32

In [30]:
random_tensor.dtype

torch.float32

In [31]:
TENSOR.dtype

torch.int64

### Create a range of tensors and tensors-like

In [32]:
torch.range(0, 10)

<ipython-input-32-cf0dcdb325c8>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [33]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
range_tensor = torch.arange(start=0, end=1000, step=77)
range_tensor

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [35]:
# Creating tensors-like
one_to_ten = torch.arange(1, 11)
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors we'll run into PyTorch & deep learning:
1. Tensors' wrong datatype,
2. Tensors' wrong device,
3. Tensors' wrong shape.

In [36]:
# Float 32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [37]:
float_32_tensor.dtype

torch.float32

In [38]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [39]:
float_16_tensor.dtype

torch.float16

In [40]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor
                               device=None, # what device is the tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [41]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [42]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [43]:
mixed_float = float_16_tensor * float_32_tensor
mixed_float

tensor([ 9., 36., 81.])

In [44]:
mixed_float.dtype

torch.float32

In [45]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [46]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (attributes)

In [47]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1916, 0.2371, 0.6854, 0.9448],
        [0.3766, 0.1049, 0.2290, 0.5803],
        [0.0839, 0.9650, 0.2312, 0.2278]])

In [48]:
some_tensor.size, some_tensor.shape, some_tensor.size()

(<function Tensor.size>, torch.Size([3, 4]), torch.Size([3, 4]))

In [49]:
print(some_tensor)
print(f"Datatype: {some_tensor.dtype}")
print(f"Shape: {some_tensor.shape}")
print(f"Device: {some_tensor.device}")

tensor([[0.1916, 0.2371, 0.6854, 0.9448],
        [0.3766, 0.1049, 0.2290, 0.5803],
        [0.0839, 0.9650, 0.2312, 0.2278]])
Datatype: torch.float32
Shape: torch.Size([3, 4])
Device: cpu


### Manipulating tensors (operations)

In [50]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [51]:
tensor * 5

tensor([ 5, 10, 15])

In [52]:
tensor - 10

tensor([-9, -8, -7])

In [53]:
torch.mul(tensor, 5)

tensor([ 5, 10, 15])

In [54]:
torch.add(tensor, 8)

tensor([ 9, 10, 11])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication,
2. Matrix multiplication (dot product).

In [55]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [56]:
# Matrix multiplication
torch.matmul(tensor, tensor) # 1*1 + 2*2 + 3*3

tensor(14)

In [57]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 770 µs, sys: 0 ns, total: 770 µs
Wall time: 777 µs


In [58]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 45 µs, sys: 8 µs, total: 53 µs
Wall time: 56.7 µs


tensor(14)

### Shape errors

Two main rules that matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> (2, 2)
* `(3, 2) @ (2, 3)` -> (3, 3)

In [59]:
tensor @ tensor

tensor(14)

In [60]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.1460, 0.0726, 0.5710],
        [0.4270, 0.1752, 0.9531],
        [0.3879, 0.1553, 0.7917]])

In [61]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B.T) # torch.mm() is an alias for torch.matmul()

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [62]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [63]:
tensor_A.shape, tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [64]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

### Finding the min, max, mean, sum, etc. (aggregation)

In [65]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [66]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [67]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [68]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [69]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [70]:
# Positional min
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [71]:
# Positional max
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshape - change the shape of a tensor
* View - return a view of input tensor but keep the same memory as original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimensions from tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted in a certain way

In [72]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [73]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [74]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [75]:
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [76]:
x_reshaped = x.reshape(5, 2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [77]:
# Change the view
z = x.view(1, 10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [78]:
# Changin z changes x because a view of a tensor shares the same memory as tensor
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [79]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [80]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [83]:
# torch.squeeze() removes all single dimensions from target tensor
x_reshaped

tensor([[ 5.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [85]:
x_reshaped = x_reshaped.reshape(1, 10)

In [86]:
x_reshaped

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [87]:
x_reshaped.shape

torch.Size([1, 10])

In [88]:
x_reshaped.squeeze()

tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [89]:
x_reshaped.squeeze().shape

torch.Size([10])

In [90]:
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [92]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previos shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Previos shape: torch.Size([10])

New tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
New shape: torch.Size([1, 10])


In [93]:
x_squeezed.unsqueeze(dim=1)

tensor([[ 5.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])

In [94]:
# torch.permute() - rearranges the dimensions of a target tensor in specified order
x_original = torch.rand(size=(224, 224, 3)) # height, width, colour channels

# Permute the original tensor to rearrange the axis or dim order
x_permuted = x_original.permute(2, 0, 1)
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [95]:
x_original[0, 0, 0]

tensor(0.9130)

In [96]:
x_original[0, 0, 0] = 1234
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(1234.), tensor(1234.))

### Indexing (selecting data from tensors)

In [97]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [98]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [99]:
# Index on the middle bracket (dim=1)
x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [100]:
x[0][0][0]

tensor(1)

In [101]:
x[0][1][1]

tensor(5)

In [102]:
# Use ":" to select all of a target dimension
x[:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [103]:
x[:, 0]

tensor([[1, 2, 3]])

In [104]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [105]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [106]:
x[0, 1, 1]

tensor(5)

In [107]:
# Get index 0 of 0th and 1st dimensions and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [108]:
x[0, 2, 2]

tensor(9)

In [120]:
x[:, :, 2]

tensor([[3, 6, 9]])

### PyTorch tensors & NumPy

In [125]:
array = np.arange(1., 8.)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [130]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [127]:
torch.arange(1., 8.).dtype

torch.float32

In [129]:
torch.from_numpy(array).type(torch.float32).dtype

torch.float32

In [131]:
# Change the value of array
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [132]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [133]:
# Change the tensor
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibillity (trying to take random out of random)

In [135]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

random_tensor_A, random_tensor_B, random_tensor_A == random_tensor_B

(tensor([[0.5402, 0.2472, 0.8599, 0.1397],
         [0.4458, 0.3778, 0.2391, 0.3641],
         [0.1368, 0.0026, 0.4839, 0.3301]]),
 tensor([[0.4187, 0.4106, 0.3149, 0.9006],
         [0.2492, 0.8110, 0.7868, 0.9164],
         [0.6769, 0.9541, 0.5372, 0.9426]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [146]:
# Let's make random but reproducible tensors
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)
random_tensor_D = torch.rand(3, 4)

random_tensor_C, random_tensor_D, random_tensor_C == random_tensor_D

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [144]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

random_tensor_C, random_tensor_D, random_tensor_C == random_tensor_D

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

### Running tensors and PyTorch objects on GPUs and making faster computations
* `!nvidia-smi`
* `torch.cuda.is_available()`

Setup device agnostic code:
* `device = "cuda" if torch.cuda.is_available() else "cpu"`

Count number of devices:
* `torch.cuda.device_count()`

CPU is the default device.

In [147]:
# Create a tensor
tensor = torch.tensor([1, 2, 3]) # on CPU
# Move tensor to GPU if available
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor_on_gpu = tensor.to(device)

In [148]:
# If tensor is on GPU, it cannot be transformed to NumPy
# tensor_on_gpu.numpy() will return an error
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
# tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()